name: Release

on:
  push:
    branches: [main]

jobs:
  ci:
    name: Test debian packaging
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Build
        run: make clean build
